name: marvel_app_flutter
description: Pet project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lints: ^2.1.0
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slidable: ^3.0.0
  flutter_secure_storage: ^8.0.0
  youtube_player_flutter: ^8.1.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
